### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by pcvonz** [LukeStonehm/LogicalDefence#1]
Burden of proof "show *my* I'm wrong.

**Comment by LukeStonehm** [comment]
Thank you kind sir! Fixing now :)

**Comment by LukeStonehm** [comment]
Update pushed, will appear in a few hours, thank you again :+1:

**Comment by nxvtcehw** [comment]
There are others:

 Spotlight "applies to am entire group"
Lie "with that women"

**Comment by LukeStonehm** [comment]
Thank you @nxvtcehw Will tend to these a bit later. Thanks very much for helping out. My proof reading skills need work :)

**Comment by LukeStonehm** [comment]
I have fixed these issues, a new build is in the works and it will soon be released. Thank you again to those that have helped :)
