### ISSUE TITLE
Appeal to Authority seems false

### ISSUE THREAD

**Issue by wolfgangus** [LukeStonehm/LogicalDefence#13]
The explanation given for appeal to authority isn't proper.

This should be the correct definition:

"An Appeal to Authority is a fallacy with the following form: Person A is (claimed to be) an authority on subject S. Person A makes claim C about subject S. Therefore, C is true."

Therefore, if a professor in economics or a minister of finance claims "x" to be a reasonable economic policy, it should not be taken as reasonable. Only the argument should be looked at. The same thing applies to scientific papers. It does not matter that if a scientist revealed it or if a highly prestigious university revealed it. All that should matter is the reasons behind it, even if a a beggar porposed a theory, which is reasonable, it should be then accepted, as it is reasonable. Authority has nothing to do with reason, and that's what "appeal to authority" tries to state.

The definition given in the app is : "Claiming something is true because an (unqualified or untrustworthy) 'expert" says it is."

Even a qualified and trustworthy expert can have fallacious reasoning. The "unqualified and "untrustworthy" clause should be replaced with "a person holding authority" or something. 

Thanks, I hope this bug gets fixed :)

**Comment by LukeStonehm** [comment]
Sorry it's taken me this long to respond, hectic life is hectic :smile: 

Will review this and let you know what I think. Thank you for taking the time to relay this to me :)

**Comment by wolfgangus** [comment]
Hey, no hurries. Anyway, it was part of my legal studies to learn about logical fallacies. I plan on adding a few more fallacies which are missing in the app so that you can review those and see if they are reasonable or not. The app seems to contain only internet talked about fallacies :P

**Comment by LukeStonehm** [comment]
For some reason, you comment did not appear here... I received it via email though :smile: 

> Hey, no hurries. Anyway, it was part of my legal studies to learn about logical fallacies. I plan on adding a few more fallacies which are missing in the app so that you can review those and see if they are reasonable or not. The app seems to contain only internet talked about fallacies :P 

There are other apps that list the fallacies, but they all really suck. None of them have a nice look, so I decided this app would be a good idea. It also helps contribute to my programming "portfolio". Companies like to see involvement in projects outside of the work place.

As for extending the fallacies, I would like to keep the app limited to formal fallacies only. Informal fallacies like "No true Scotsman" are too loose, if that makes sense.

Will be working on the app this weekend, need to do a pull request for the recently created US English localization. I will include the corrections you have pointed out.

Thank you very much for your help, and please feel free to contribute more :smile: Have a great weekend!

**Comment by LukeStonehm** [comment]
I have changed the definition of the "appeal to authority" fallacy as you have stated. The case you have made makes sense to me, and so I have actioned on it. Thank you very much for the help, you will see it in the next release :smile:
