### ISSUE TITLE
Add translations support

### ISSUE THREAD

**Issue by glenux** [LukeStonehm/LogicalDefence#2]
Having the text translated in other languages would be awesome.
It should probably depend on system preferences for default choice.

P.S: I can help for translating in french.

**Comment by LukeStonehm** [comment]
This is a damn fine idea, I cannot believe I did not consider it myself... 

I will get to work right away on this (in around my studies and my job). I will contact you once I have learnt how to use the built in locale feature that Android has.

**Comment by LukeStonehm** [comment]
@glenux I've worked out how to use the built in translation editor, so the next step is that I'm going to use Google Translate to get a rough translation of every string in the code, then if you would help correct the mistakes (for French) that would be appreciated.

**Comment by LukeStonehm** [comment]
@glenux I have released a new build to the Play Store, and it includes French locale support. I used Google Translate as I said I would, but I would appreciated it if you would proof read it for me. There will be mistakes, in fact, there may be sentences that make no sense whats so ever :laughing: 

Thanks again for your support :smile:

**Comment by Elinvention** [comment]
This app is awesome! I am going to translate it in Italian, so that all my friends can read it. Expect a pull request soon. Thank you!

**Comment by LukeStonehm** [comment]
@Elinvention All help is appreciated! Thank you very much for your support. Be sure to also translate the Play Store listing strings I have just recently added (in the root of the project :smile: )

Thank you again!

**Comment by LukeStonehm** [comment]
Thank you to all the people who have done translations thus far! Highly appreciated. I'm going to close down this issue. I will deal with each language request as they come in, or simply accept pull requests :smile:
