### ISSUE TITLE
Translate new strings

### ISSUE THREAD

**Issue by LukeStonehm** [LukeStonehm/LogicalDefence#31]
@Swyter  @N07070   @aberlin   @Elinvention @etnadji 

If you have a chance, this is just a friendly request to have the new strings translated into the respectable languages please. 

Please see the following commits for the strings:
xml files
548e5cf41e0b868f268156852e14171745ab6ec9 

play store listing strings
2b609bda5072741c27a81d17e538a691e17939fe

Thanks very much :smile:

**Comment by N07070** [comment]
Working on it

**Comment by Swyter** [comment]
Same!

**Comment by Swyter** [comment]
Done! See pull request #32.

**Comment by LukeStonehm** [comment]
You guys rock! Thank you very much :+1:

**Comment by LukeStonehm** [comment]
Going to release the changes from @Swyter & @N07070  now.

Hopefully the other guys help as well :smile:

**Comment by N07070** [comment]
You're welcome :smile:

**Comment by LukeStonehm** [comment]
Seems like all languages have been updated! Thanks guys, have a good week :smile:
