### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by jm56** [LukeStonehm/LogicalDefence#42]
Hi, I would be happy to fix some issues in the french translation if you want. It is a great app! :)
Jonathan

**Comment by LukeStonehm** [comment]
Hi there. Please, by all means, go ahead and fix things :smile: I would really appreciated it, as well as our French speaking users. Simply submit a pull request and I will be happy to merge it in.

**Comment by LukeStonehm** [comment]
Thanks again!
