### ISSUE TITLE
Misleading Vividness Typo

### ISSUE THREAD

**Issue by dperreault** [LukeStonehm/LogicalDefence#60]
Just installed from app store and the misleading Vividness entry reads 
Misleading Vividness

Describing an occurrence in vivid detail, even if it is a rare occurrence, to convince someone that it is a true.

"...that it is a true", while cute, is not quite correct.

**Comment by LukeStonehm** [comment]
Thanks very much for picking this up, I will correct it upon the next release. 👌

**Comment by LukeStonehm** [comment]
This has been solved thanks to @alt-shreya
