### ISSUE TITLE
I just want to make sure.

### ISSUE THREAD

**Issue by jol09** [LukeStonehm/LogicalDefence#66]
Hi.
previously I am very grateful for the owner of the Logical Defense project.

I would like to ask you basic issues related to Logical Defense Logo. I see the logo is too complicated. and difficult to remember. but every logo has a meaning, and every logo is perfectly designed. but before I say anything else. is there any meaning of the existing logo.
I just want to make sure.

**Comment by D-side** [comment]
In a way, the README answers this already;

> Brain icon was found on Icon Finder - https://www.iconfinder.com/icons/190293/brain_games_icon (could not find the author's website)

I suppose that's all there is to it. It's a brain. The part of a human body responsible for logical reasoning, and thus most relevant to this app.
