### ISSUE TITLE
Share function

### ISSUE THREAD

**Issue by LukeStonehm** [LukeStonehm/LogicalDefence#7]
It has been recommended that I add a share function on long press on each fallacy. I will be doing this :)

**Comment by LukeStonehm** [comment]
@aberlin gave this input in another issue.

https://github.com/LukeStonehm/LogicalDefence/issues/23

sometimes it would be useful to have the ability to share a logical fault in a chat.

This could be a start for an Implementation:
http://stackoverflow.com/questions/5646104/how-to-implement-the-share-function-of-a-android-app#5646627

**Comment by Korpip** [comment]
For now just putting it into the clipboard could be easier.

**Comment by LukeStonehm** [comment]
App updated, pushed to play store. You can now long-press an item and it will use the built in text share intent :smile: You can then share it will pretty much any app.
